[FEATURE] Pouvoir modifier un test statique existant (PIX-7797)
1024pix/pix-editor pull request #127
Opened 2023-07-11 15:41 UTC by laura-bergoens

## :unicorn: Problème
EPIC tests statiques

## :robot: Solution
Possibilité de modifier un test statique en cliquant sur le bouton d'édition depuis la page de détails dudit test.
Vérifications de permissions et de validation de champs identiques à la création.

## :rainbow: Remarques
On profitera de l'édition d'un test statique pour le déplacer dans la base PG.

RESTE A FAIRE :
le css sur la page d'édition n'a pas fonctionné comparé aux autres pages (le header, le body est bizarre)

## :100: Pour tester
Se rendre sur la page de détails d'un test statique, l'éditer.

2023-07-13 08:40 UTC, nlepage approved these changes
LGTM

2023-07-13 08:40 UTC, nlepage commented on api/lib/application/static-courses/static-courses.js
> +  }
**question:** Ça ne pourrait pas aller aussi dans `staticCourseToUpdate.update()` ?

2023-07-13 08:40 UTC, nlepage commented on api/lib/infrastructure/repositories/static-course-repository.js
> +// TODO: when double read will be removed, move pagination process into knex
**nitpick:** ce TODO n'est pas pertinent ici

2023-07-13 08:40 UTC, nlepage commented on pix-editor/app/components/form/static-course.js
> +export default class StaticCourseForm extends Component {
**suggestion:** Remonter cette classe en haut du fichier ?

2023-07-13 08:40 UTC, nlepage commented on pix-editor/app/models/static-course.js
> +  // TODO : i hate this approach pls help
**question:** quel est le problème ?

2023-07-13 08:40 UTC, nlepage commented on pix-editor/app/routes/authenticated/static-courses/static-course/details.js
> +      mayEditStaticCourse: this.access.mayCreateOrEditStaticCourse(),
**question:** Est-ce que ça a vraiment sa place dans le model ?

Le controller pourrait aussi bien s'injecter `access` pour y accéder directement non ?

2023-07-13 12:49 UTC, laura-bergoens commented on api/lib/application/static-courses/static-courses.js
> +  }
de quoi parles-tu, du check que le static course existe ? pô compris

2023-07-13 13:45 UTC, laura-bergoens commented on pix-editor/app/models/static-course.js
> +  // TODO : i hate this approach pls help
Ben je trouve qu'il y a une considération de "présentation" qui est mise dans le modèle Ember, ça ne me plait pas.
J'aurais aimé le mettre dans le controller ou quoi mais ou bien on peut pas ou bien j'arrive pas à comprendre le fonctionnement du helper 'fn'

2023-07-13 13:47 UTC, laura-bergoens commented on pix-editor/app/routes/authenticated/static-courses/static-course/details.js
> +      mayEditStaticCourse: this.access.mayCreateOrEditStaticCourse(),
Oui aussi.
Après il est dit des routeurs qu'ils sont supposés retourner toutes les données nécessaires à l'affichage du template sous-jacent, donc en l'occurrence cette valeur permet de régir l'activation/désactivation du bouton.
Je vais voir si dans la doc Ember ils sont plus clairs là-dessus.

2023-07-13 16:16 UTC, laura-bergoens commented on pix-editor/app/routes/authenticated/static-courses/static-course/details.js
> +      mayEditStaticCourse: this.access.mayCreateOrEditStaticCourse(),
https://guides.emberjs.com/release/routing/controllers/

Je trouve que là-dessus ça a l'air d'aller dans le sens de ma proposition.

> The Controller is then often used to decorate the model with display properties such as retrieving the full name from a name model.

> Controllers are used as an extension of the model loaded from the Route. Any attributes or actions that we want to share with components used on that Route could be defined on the Controller and passed down through the Route’s template.

En fait plus généralement je trouve que le Controller, si il a besoin de faire appel à des services, c'est parce que sur la page y aurait eu une action utilisateur pour laquelle il a besoin d'infos supplémentaires pour prendre une décision.
Là, je cherche d'emblée à savoir si je dois afficher mon bouton ou pas (au rendu initial) donc ça me paraît être une donnée root obligatoire.
WDYT de mon pavé ? 🧱

2023-07-17 07:53 UTC, nlepage commented on pix-editor/app/routes/authenticated/static-courses/static-course/details.js
> +      mayEditStaticCourse: this.access.mayCreateOrEditStaticCourse(),
OK ça me va :+1:

2023-07-17 07:55 UTC, nlepage commented on api/lib/application/static-courses/static-courses.js
> +  }
Oui c'est ça, déplacer ce `if` dans `staticCourseToUpdate.update()`.

2023-07-17 08:15 UTC, laura-bergoens commented on api/lib/application/static-courses/static-courses.js
> +  }
je comprends pas trop comment c'est possible vu que le staticCourseToUpdate est une instance récupérée a priori parce qu'il existe.
Où alors tu penses à une stratégie de null object ?

2023-07-17 09:21 UTC, nlepage commented on pix-editor/app/models/static-course.js
> +  // TODO : i hate this approach pls help
J'ai poussé un commit qui bouge le getter dans le controller, je te laisse voir, mais ça fonctionne.

2023-07-17 09:53 UTC, alixdeschamps requested changes
il y a un bug lors de l'édition d'un test statique. La description disparait quand j'édite une deuxième fois : https://www.loom.com/share/d813f737f8b14a3a99046fcc2de9874c?sid=536b80a6-259e-40ac-a2bd-24d1412a8b65

2023-07-17 11:00 UTC, laura-bergoens commented on pix-editor/app/templates/authenticated/static-courses/static-course/edit.hbs
> +      @initialChallengeIds={{this.challengeIdsAsStringWithBreakLines}}
AH, en mode getter, okayyyyyyyyyy
merci

2023-07-17 11:00 UTC, laura-bergoens commented on pix-editor/app/models/static-course.js
> +  // TODO : i hate this approach pls help
ok pour moi

2023-07-17 11:13 UTC, laura-bergoens commented
> il y a un bug lors de l'édition d'un test statique. La description disparait quand j'édite une deuxième fois : https://www.loom.com/share/d813f737f8b14a3a99046fcc2de9874c?sid=536b80a6-259e-40ac-a2bd-24d1412a8b65

Fixed !

2023-07-17 12:19 UTC, alixdeschamps requested changes
ca fail quand je clique sur Editer sur ce test statique :https://pix-lcms-review-pr127.osc-fr1.scalingo.io/static-courses/reclu1Fg8x6nDCMpv
![Screenshot 2023-07-17 at 14 19 30](https://github.com/1024pix/pix-editor/assets/9588479/3688d435-7ece-4a43-92d5-4c74b01a7b07)

2023-07-17 12:24 UTC, nlepage commented on api/lib/application/static-courses/static-courses.js
> +  }
Ah oui effectivement je n'avais pas bien le code désolé.

2023-07-18 13:08 UTC, jujumathieu commented
Tout m'a l'air bon excepté l'affichage de la description qui ne tient par compte des sauts de ligne

2023-07-19 12:31 UTC, alixdeschamps approved these changes
LGTM

2023-07-19 12:31 UTC, merged