[TECH] Ajout d'un script permettant de passer des épreuves en focus via une liste d'acquis (PIX-2962).
1024pix/pix-editor pull request #206
Opened 2021-08-12 13:21 UTC by VincentHardouin

## :unicorn: Problème
Nous avons une nouvelle modalité d'épreuve : focus. Nous souhaitons passés un certain nombre d'épreuves en focus, mais cela nécessite de nombreuses étapes et engendrer des erreurs.   

## :robot: Solution
Créer un script permettant de passer toutes les épreuves d'un acquis en focus. 

Ce script prend une liste d'acquis (id persistant) via un fichier csv. 

## :rainbow: Remarques
- Seulement les épreuves : `validé`, `validé sans test`, `pré-validé` sont dupliquées. 
- Les pièces-jointes sont aussi dupliquées.
- Les anciens acquis et leurs épreuves sont passés en `archivé`.
- Les nouveaux acquis sont passés en `actif`. 

## :100: Pour tester
- Copier la branche en local.
- Utiliser la base Airtable copy. 
- Lancer la commande avec les variables d'environnement remplies (demander à l'équipe) : 
```shell
AIRTABLE_API_KEY=<> AIRTABLE_BASE=<> TOKEN_URL=<> BUCKET_NAME=<> BUCKET_PASSWORD=<> STORAGE_TENANT=<> BUCKET_USER=<> node index.js
```

2021-08-12 13:25 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://pix-lcms-review-pr206.osc-fr1.scalingo.io
- API: https://pix-lcms-review-pr206.osc-fr1.scalingo.io/api/

 Please check it out!

2021-08-13 08:57 UTC, sbedeau requested changes
1ère revue technique pour le clean code
Je ferai une 2ème revue de compréhension après mais je n'ai rien vu de choquant en lecture rapide sur le fonctionnement.
Fonctionnellement, je pense qu'on devrait faire le déroulé tous ensemble pour gagner du temps, de la compréhension et éviter les erreurs

2021-08-13 08:57 UTC, sbedeau commented on scripts/package.json
> +    "@samwen/base62-util": "^1.0.4",
**question:** À t'on vraiment besoin de ce paquet ? On est sûr de vouloir une dépendance de cette nature (pas d'étoiles, pas de DL, etc.) ?

2021-08-13 08:57 UTC, sbedeau commented on scripts/package.json
> +    "js-crypto-random": "^1.0.2",
**question:** Je comprend l'utilité de ce paquet mais est-ce qu'on en a vraiment besoin ?

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
> +        maxRecords: 1
**chipotage (sur tout le fichier):** Extraire dans une variable qui explicite la nature des résultats attendus

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
> +      nock.disableNetConnect();
**question:** Pourquoi est-ce le seul endroit où l'on a besoin de ces lignes ? 

**suggestion:** Utiliser ces lignes dans un `beforeEach`/`afterEach` pour le fichier

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +    maxRecords: 1,
**chipotage (pour tout le fichier):** Nommer explicitement le await dans une constante et retourner le résultat

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +    ],
**suggestion:** Extraire les fields dans une variable pour améliorer la lisibilité

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +    };
**chipotage:** Extraire des méthodes pour faciliter la lecture

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +async function main() {
**chipotage:** Appliquer la stepdown rule

2021-08-13 08:57 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +};
**chipotage:** Ces méthodes ne devraient pas être exposées et importables compte tenu de leur localité dans un script

2021-08-13 09:05 UTC, VincentHardouin commented on scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
> +      nock.disableNetConnect();
Ils ont été enlevé du `beforeEach` suite au lint due à `plugin:mocha/recommended`

2021-08-13 09:07 UTC, VincentHardouin commented on scripts/package.json
> +    "@samwen/base62-util": "^1.0.4",
On a pris le choix d'utiliser la même idGenerator que Pix Editor (même remarque pour `js-crypto-random`.

2021-08-13 12:13 UTC, sbedeau commented on scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
> +      nock.disableNetConnect();
On a enlevé la règle associées sur API car c'est juste un warning et on l'utilise souvent

2021-08-13 12:27 UTC, VincentHardouin commented on scripts/copy-skills-and-set-challenges-as-focusable/index-tests.js
> +      nock.disableNetConnect();
Règle ajoutée, et beforeEach remis

2021-08-13 13:07 UTC, alexandrecoin reviewed
Ok pour la partie tech, mais preneur d'un point de groupe comme mentionné par Stéphane pour toute la partie fonctionnelle. 

PS: GG, sacré morceau 💪

2021-08-17 08:11 UTC, francois2metz approved these changes
:grapes: :melon: :tangerine: :pineapple: :apple: :kiwi_fruit: LGTM :kiwi_fruit: :apple:  :pineapple:  :tangerine:  :melon: :grapes:

2021-08-17 09:58 UTC, Thomasevano approved these changes

2021-08-19 09:13 UTC, celineung approved these changes

2021-08-19 12:39 UTC, sbedeau reviewed
Dommage que mon commentaire soit laissé sans considération

2021-08-19 12:44 UTC, VincentHardouin commented on scripts/copy-skills-and-set-challenges-as-focusable/index.js
> +async function main() {
On ne l'applique pas spécialement chez Pix

2021-08-19 13:02 UTC, merged