[DOC] Améliorer la documentation (`sample.env`, `README.md`, `INSTALL.md`).
1024pix/pix-editor pull request #21
Opened 2022-01-24 16:22 UTC by jbuget

## :unicorn: Problème
L'installation des applications LCMS (Pix Editor, et LCMS API) est compliquée, notamment par défaut de documentation.

## :robot: Solution
- Mettre à jour le fichier `sample.env` pour ajouter / supprimer / définir les variables d'environnement nécessaires au bon fonctionnement de l'application LCMS API
- Améliorer la documentation de la partie "Installation" (en l'occurrence, cette section a été déportée dans un nouveau fichier `INSTALL.md`)

## :rainbow: Remarques
> La documentation, c'est relou, mais nécessaire.

## :100: Pour tester
Vérifier l'installation en local sur son poste.

2022-01-24 16:26 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://pix-lcms-review-pr21.osc-fr1.scalingo.io
- API: https://pix-lcms-review-pr21.osc-fr1.scalingo.io/api/

 Please check it out!

2022-01-24 16:49 UTC, thetinyspark approved these changes
LGTM

2022-01-24 16:49 UTC, francois2metz approved these changes
:snowflake: :snowman: :skier: :mount_fuji: :christmas_tree:  LGTM :christmas_tree:  :mount_fuji: :skier: :snowman: :snowflake:

2022-01-24 17:05 UTC, Jeremiejade requested changes

2022-01-24 17:05 UTC, Jeremiejade commented on pix-editor/README.md
Le port pour lancer les tests ne me semble pas être le bon :
`* Visit your tests at [http://localhost:4300/tests](http://localhost:4300/tests).`

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +Dans un premier processus ou terminal, depuis le répertoire `~/pix-editor`:
**suggestion**
```suggestion
Dans un second processus ou terminal, depuis le répertoire `~/pix-editor`:
```

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +(cd api && npm run db:reset)
**question**
Pourquoi la deuxième ligne est-elle entre parenthèse ? Est-ce qu'il faut l'executer ou pas ?

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +$ git clone git@github.com:1024pix/pix-editor.git && cd pix-editor
**nitpick**
Il y a parfois des `$` avec les commandes shell, parfois non. Pour être cohérent, je suggère de les enlever partout (c'est embêtant quand on veut copier-coller plusieurs lignes).

```suggestion
git clone git@github.com:1024pix/pix-editor.git && cd pix-editor
```

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +$ npm ci
**nitpick**
Il faut être revenu au dossier racine à la commande d'après.

```suggestion
cd api
npm ci
cd ..
```

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +$ npm ci
**nitpick**
Idem

```suggestion
cd pix-editor
npm ci
cd ..
```

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +$ npm start
**nitpick**
Pour être cohérent

```suggestion
cd api
npm start
```

2022-01-24 17:18 UTC, iwazaru commented on INSTALL.md
> +> Par défaut, et en local, utiliser l'un des 2 jetons renseignés dans le fichier `~/api/db/seeds/seed.js` (cf. `defaultUserApiKey` [admin] et `defaultEditorUserApiKey` [éditeur]) pour s'authentifier
```suggestion
> Par défaut, et en local, utiliser l'un des 2 jetons renseignés dans le fichier `./api/db/seeds/seed.js` (cf. `defaultUserApiKey` [admin] et `defaultEditorUserApiKey` [éditeur]) pour s'authentifier dans l'interface de connexion.
```

2022-01-24 17:25 UTC, iwazaru commented on INSTALL.md
> +> Les versions indiquées sont celles préconisées pour un bon fonctionnement de l'application.
**nitpick**
Redondant

```suggestion
⚠️ Les versions indiquées sont celles utilisées et préconisées par l'équipe de développement. Il est possible que l'application fonctionne avec des versions différentes.
```

2022-01-24 17:26 UTC, iwazaru commented
J'ai fait test fonctionnel en suivant les instructions, j'arrive à m'identifier puis j'ai une page blanche avec cette erreur dans la console :

```
Error while processing route: index Ember Data Request GET /api/airtable/content/Referentiel returned a 404
```

Est-ce à ce moment-là qu'il faut contacter l'équipe de développement pour obtenir la structure de la base ? Si oui, ça vaut le coup de le préciser je pense, car beaucoup risquent de bloquer à cet endroit.

2022-01-25 14:18 UTC, jbuget commented on INSTALL.md
> +(cd api && npm run db:reset)
Oui, il faut exécuter la ligne entièrement, en gardant bien les parenthèses.

En Unix - je ne suis pas expert et je raconte ce que j'ai toujours déduit - la parenthèse permet de se déplacer _virtuellement_ (ou via un sous-process) dans le répertoire et donc au sortir de la ligne d'instruction, tu n'as pas besoin de faire `cd ..`, tu es automatiquement remis sur le répertoire depuis lequel tu as effectué la commande. 

En l'occurrence ici, je reste au niveau de la racine du projet.

2022-01-25 14:18 UTC, jbuget commented on INSTALL.md
> +$ git clone git@github.com:1024pix/pix-editor.git && cd pix-editor
+1. Bien vu. Je m'en occupe.

2022-01-25 14:19 UTC, jbuget commented on INSTALL.md
> +$ npm ci
Un exemple ici de l'utilité des parenthèses.

2022-01-25 14:19 UTC, jbuget commented on INSTALL.md
> +$ npm ci
Idem ;-)

2022-01-25 14:19 UTC, jbuget commented on INSTALL.md
> +$ npm start
ok

2022-01-25 14:21 UTC, jbuget commented on INSTALL.md
> +> Par défaut, et en local, utiliser l'un des 2 jetons renseignés dans le fichier `~/api/db/seeds/seed.js` (cf. `defaultUserApiKey` [admin] et `defaultEditorUserApiKey` [éditeur]) pour s'authentifier
J'ai pris l'habitude d'utilise la tilde pour définir la racine du projet (sûrement une habitude des imports Ember dans l'ancien temps).

Le `.` me paraît trop volatile, pouvant signifier trop de choses à mon sens.

Je ne suis pas pour changer, mais si tu/on me redis/dit que c'est mieux, je prends.

2022-01-25 14:21 UTC, jbuget commented on INSTALL.md
> +> Les versions indiquées sont celles préconisées pour un bon fonctionnement de l'application.
Bien vu.

2022-01-25 14:28 UTC, iwazaru commented on INSTALL.md
> +(cd api && npm run db:reset)
Merci, j'ai appris un truc !

2022-01-25 14:33 UTC, jbuget commented on INSTALL.md
> +(cd api && npm run db:reset)
Un poil plus de précision [ici](https://stackoverflow.com/a/21929112).

2022-01-25 14:37 UTC, iwazaru commented on INSTALL.md
> +> Par défaut, et en local, utiliser l'un des 2 jetons renseignés dans le fichier `~/api/db/seeds/seed.js` (cf. `defaultUserApiKey` [admin] et `defaultEditorUserApiKey` [éditeur]) pour s'authentifier
Pour expliciter ma suggestion : pour moi le tilde renvoie à mon dossier personnel, et si je fais `vim ~/api/db/seeds/seed.js` ça va ouvrir le fichier `/Users/clement/api/db/seeds/seed.js`. Il me semble que `.` pour le dossier courant et `~` pour le dossier personnel sont des conventions Unix ?

2022-01-25 14:44 UTC, jbuget commented on INSTALL.md
> +> Par défaut, et en local, utiliser l'un des 2 jetons renseignés dans le fichier `~/api/db/seeds/seed.js` (cf. `defaultUserApiKey` [admin] et `defaultEditorUserApiKey` [éditeur]) pour s'authentifier
Ahhhh effectivement… je ne prends pas en compte ce cas là dans ma tête… Là il s'agit plus de conventions de lecture (et encore, elles sont avant tout très personnelles). Mais c'est vrai que ce n'est pas un réflexe pour tout le monde (personne ?). Je change. Merci de la précision.

2022-01-25 15:23 UTC, jbuget commented
> J'ai fait test fonctionnel en suivant les instructions, j'arrive à m'identifier puis j'ai une page blanche avec cette erreur dans la console :
> 
> ```
> Error while processing route: index Ember Data Request GET /api/airtable/content/Referentiel returned a 404
> ```
> 
> Est-ce à ce moment-là qu'il faut contacter l'équipe de développement pour obtenir la structure de la base ? Si oui, ça vaut le coup de le préciser je pense, car beaucoup risquent de bloquer à cet endroit.

Juste remarque. Merci du retour. Je pense qu'il est préférable d'inciter à "contacter l'équipe support via le centre d'aide".

2022-01-25 15:45 UTC, Jeremiejade approved these changes
LGTM

2022-01-26 14:56 UTC, merged