[TECH] Remplacer Bunyan et les plugins Good, Good-console, Good-squeeze qui ont été dépréciées par Pino et Hapi-pino (PIX-3451)
1024pix/pix-editor pull request #220
Opened 2021-09-14 13:21 UTC by yahyayouness

## :unicorn: Problème
Les plugins good, good-console, good-squeeze ont été déprécié depuis 20/12/2020.

## :robot: Solution
Remplacer ces plugins par hapi-pino.
Comme hapi-pino utilise pino, on remplace donc bunyan par pino.

## :rainbow: Remarques
Cette PR va garder le comportement par défault du plugin hapi-pino. Une adaptation sera faite coté datadog.
On perd la métrique `route` (à l'image du index.js, ex /users/${id}/foo) qui va être enrichie dans une autre PR.
Pour la métrique event response, il sera mappé dans datadog en se basant sur l'attribut  "msg": "request completed".
J'ai gardé l'event error qui affiche la stacktrace dans un log dédié corrélé par un id de la requête qui en question. On verra par la suite si on veut l'enlever.
Le logger bunyan a été remplacé par le logger pino et la même instance de log a été utilisée par hapi-pino. 
Avec hapi-pino on peut customiser facilement l'objet request remontée dans les logs Datadog, ce qui va nous permettre d'avoir une entrée de logs enrichie avec tous les métriques nécessaires qu'on veut monitorer.

## :100: Pour tester

1. Vérifier en lançant un `npm run test:api:acceptance` que les logs ne sont pas affichés lors des tests.
2. Lancer l'API en locale avec les deux modes dev et production:

Avec un NODE_ENV=developpement npm start , on obtient le log ci-dessous avec l'option prettyPrint pour l'event response:

```
[1630520764051] INFO (7819 on MacBook-Pro-de-yahya.local): request completed
    queryParams: {}
    req: {
      "id": "1630520764034:MacBook-Pro-de-yahya.local:7819:kt1tyl3x:10000",
      "method": "get",
      "url": "/api/admin/users/1",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.54.0",
        "accept": "*/*"
      },
      "remoteAddress": "127.0.0.1",
      "remotePort": 50157
    }
    res: {
      "statusCode": 401,
      "headers": {
        "content-type": "application/json; charset=utf-8",
        "vary": "origin",
        "access-control-expose-headers": "WWW-Authenticate,Server-Authorization",
        "cache-control": "no-cache",
        "content-length": 63
      }
    }
    responseTime: 17
```

Avec un NODE_ENV=production npm start , on obtient le json ci-dessous non formaté pour l'event response:

```
{
  "level": 30,
  "time": 1630520449140,
  "pid": 7495,
  "hostname": "MacBook-Pro-de-yahya.local",
  "queryParams": {},
  "req": {
    "id": "1630520449119:MacBook-Pro-de-yahya.local:7495:kt1trufs:10000",
    "method": "get",
    "url": "/api/admin/users/1",
    "headers": {
      "host": "localhost:3000",
      "user-agent": "curl/7.54.0",
      "accept": "*/*"
    },
    "remoteAddress": "127.0.0.1",
    "remotePort": 50128
  },
  "res": {
    "statusCode": 401,
    "headers": {
      "content-type": "application/json; charset=utf-8",
      "vary": "origin",
      "access-control-expose-headers": "WWW-Authenticate,Server-Authorization",
      "cache-control": "no-cache",
      "content-length": 63
    }
  },
  "responseTime": 20,
  "msg": "request completed"
}
```

Et une entrée pour l'event OPS qui n'as pas changé de contrat d'interface par rapport à Good:

```
{
  "level": 30,
  "time": 1630520553900,
  "pid": 7495,
  "hostname": "MacBook-Pro-de-yahya.local",
  "tags": [
    "ops"
  ],
  "data": {
    "host": "MacBook-Pro-de-yahya.local",
    "osload": [
      2.17333984375,
      2.34814453125,
      2.49560546875
    ],
    "osmem": {
      "total": 17179869184,
      "free": 922202112
    },
    "osup": 3872,
    "psup": 113.927457659,
    "psmem": {
      "rss": 126742528,
      "heapTotal": 73125888,
      "heapUsed": 69779264,
      "external": 5699557,
      "arrayBuffers": 4111622
    },
    "pscpu": {
      "user": 3963525,
      "system": 605791
    },
    "psdelay": 0.2529459996148944,
    "requests": {
      "3000": {
        "total": 0,
        "disconnects": 0,
        "statusCodes": {}
      }
    },
    "responseTimes": {
      "3000": {
        "avg": null,
        "max": 0
      }
    },
    "sockets": {
      "http": {
        "total": 0
      },
      "https": {
        "total": 0
      }
    }
  }
}
```
En simulant une API en ERROR:

On obtient la sortie suivante:

```
{
  "level": 50,
  "time": 1630573781837,
  "pid": 12453,
  "hostname": "MacBook-Pro-de-yahya.local",
  "err": {
    "type": "Error",
    "message": "toto",
    "stack": "Error: toto\n    at authenticateUser (/Users/you-octo/Desktop/repositories/pix/api/lib/application/authentication/authentication-controller.js:15:11)\n    at exports.Manager.execute (/Users/you-octo/Desktop/repositories/pix/api/node_modules/@hapi/hapi/lib/toolkit.js:57:29)\n    at Object.internals.handler (/Users/you-octo/Desktop/repositories/pix/api/node_modules/@hapi/hapi/lib/handler.js:46:48)\n    at exports.execute (/Users/you-octo/Desktop/repositories/pix/api/node_modules/@hapi/hapi/lib/handler.js:31:36)\n    at Request._lifecycle (/Users/you-octo/Desktop/repositories/pix/api/node_modules/@hapi/hapi/lib/request.js:372:68)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Request._execute (/Users/you-octo/Desktop/repositories/pix/api/node_modules/@hapi/hapi/lib/request.js:280:9)",
    "isBoom": true,
    "isServer": true,
    "data": null,
    "output": {
      "statusCode": 500,
      "payload": {
        "statusCode": 500,
        "error": "Internal Server Error",
        "message": "An internal server error occurred"
      },
      "headers": {}
    }
  },
  "msg": "request error"
}
{
  "level": 30,
  "time": 1630573781837,
  "pid": 12453,
  "hostname": "MacBook-Pro-de-yahya.local",
  "queryParams": {},
  "req": {
    "id": "1630573781834:MacBook-Pro-de-yahya.local:12453:kt2pi7mj:10001",
    "method": "post",
    "url": "/api/token",
    "headers": {
      "host": "localhost:3000",
      "user-agent": "curl/7.54.0",
      "accept": "*/*",
      "accept-encoding": "deflate, gzip",
      "content-length": "79",
      "content-type": "application/x-www-form-urlencoded"
    },
    "remoteAddress": "127.0.0.1",
    "remotePort": 51705
  },
  "res": {
    "statusCode": 500,
    "headers": {
      "content-type": "application/json; charset=utf-8",
      "vary": "origin",
      "access-control-expose-headers": "WWW-Authenticate,Server-Authorization",
      "cache-control": "no-cache",
      "content-length": 96
    }
  },
  "responseTime": 3,
  "msg": "request completed"
}
```

2021-09-14 13:25 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://pix-lcms-review-pr220.osc-fr1.scalingo.io
- API: https://pix-lcms-review-pr220.osc-fr1.scalingo.io/api/

 Please check it out!

2021-09-15 06:44 UTC, jbuget requested changes
Ne pas mettre des insrtuctions `if env.isProduction` dans le code (hors fichier de config)

2021-09-15 06:44 UTC, jbuget commented on api/lib/config.js
> +    isProduction: ['production'].includes(process.env.NODE_ENV),
⚠️ Attention, le fichier et le mécanisme de `config.js` a été pensé pour éviter d'avoir ce genre d'implémentation qui met des `if production` dans le code. 

On ne doit pas faire ça. Car si une option dépend exclusivement d'un environnement, on risque d'être tenté à un moment, peut-être de façon temporaire et pour résoudre un problème, de basculer l'environnement vers la prod, et si on a plusieurs endroits comme ça dans le code, de créer des effets de bord négatifs incontrôlés.

On doit plutôt faire `if feature.enabled…` ou `if feature.option…`.

2021-09-15 06:44 UTC, jbuget commented on api/lib/infrastructure/logger.js
> +  prettyPrint: !settings.isProduction,
Ici par exemple, je verrais plutôt `if config.logging.isPrettyPrint`.

2021-09-15 06:44 UTC, jbuget commented on api/server.js
> +  if (config.isProduction) await enableOpsMetrics(server);
Idem

2021-09-20 07:32 UTC, francois2metz approved these changes
:rose: :hibiscus: :white_flower: :wilted_flower:  :tulip: :sunflower: :cherry_blossom:  LGTM :cherry_blossom: :sunflower:  :tulip: :wilted_flower: :white_flower: :hibiscus: :rose:

2021-09-20 08:09 UTC, jonasgrilleres approved these changes

2021-09-21 14:26 UTC, merged