[FEATURE] Ajouter les liens vers la thématique parente et les acquis enfants sur le modèle Tube de la release (PIX-6331)
1024pix/pix-editor pull request #73
Opened 2022-11-15 15:16 UTC by laura-bergoens

## :unicorn: Problème
Le référentiel est un arbre. Mais dans le modèle TubeForRelease, il manque des branches pour naviguer facilement, en l'occurrence vers son parent direct, _**la thématique**_, et ses enfants **_les acquis_**.

## :robot: Solution
Ajouter ces informations à la création de la release

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
Vérifier un payload de récupération de release après création et s'assurer que les liens sont présents

2022-11-15 16:09 UTC, pix-service commented
I'm deploying this PR to these urls:

- App: https://pix-lcms-review-pr73.osc-fr1.scalingo.io
- API: https://pix-lcms-review-pr73.osc-fr1.scalingo.io/api/

 Please check it out!

2022-11-21 11:29 UTC, Jeremiejade commented on api/tests/unit/domain/models/Content_test.js
> +      tubeAirtable.skillIds = ['recSkillA'];
Quelque chose m'échappe, je ne comprends pas pourquoi on doit ajouter ces champs ici qui ne viennent pas de airTable.  Je vois que tu as laissé un ` //Todo`,  ça à peut etre un lien.

2022-11-21 11:29 UTC, Jeremiejade approved these changes

2022-11-21 13:26 UTC, Jeremiejade requested changes
J'ai un bug lors de la creation de la release en locale. j'annule ma coche

2022-11-22 08:51 UTC, laura-bergoens commented
@Jeremiejade C'est bon, c'est parce qu'il fallait gérer le cas de thématiques qui n'ont pas de tubes (🤯)

Et concernant le TODO, je pense qu'il faut carrément supprimer tout le fichier de test, je peux expliquer à l'oral pourquoi, à l'écrit c'est embêtant 😓

2022-11-22 11:12 UTC, Jeremiejade approved these changes

2022-11-22 13:04 UTC, merged